site_name: ECO309

nav:
- Introduction: notebooks/0_General_Introduction.ipynb
- System: linux_and_git.md
- Optimization: optim_slides.md
- Dynamic Programming: discrete_dynamic_programming.md

theme:
  name: material
  feature:
    tabs: true


plugins:
  - mknotebooks

markdown_extensions:
  - mdx_math
  - markdown_inline_graphviz
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.highlight:
      use_pygments: true
      extend_pygments_lang: [yaml]
  - pymdownx.superfences

# extra_css:
#     - css/extra.css


extra_javascript:
  # other extra java script
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
